/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import java.util.Arrays;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import jdk.nashorn.internal.ir.ContinueNode;

/**
 *
 * @author BKTECH
 */
public class Inicio extends javax.swing.JFrame {
    String[] vogais = {"a","e","i","o","u"}; 

    /**
     * Creates new form NovoJFrame
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextFieldVogal1 = new javax.swing.JTextField();
        TextFieldCripto1 = new javax.swing.JTextField();
        btn_criptografar = new javax.swing.JButton();
        label_vogal1 = new javax.swing.JLabel();
        label_cripto1 = new javax.swing.JLabel();
        label_cripto2 = new javax.swing.JLabel();
        label_vogal2 = new javax.swing.JLabel();
        TextFieldCripto2 = new javax.swing.JTextField();
        TextFieldVogal2 = new javax.swing.JTextField();
        btn_descriptografar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_criptografar.setText("Criptografar");
        btn_criptografar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_criptografarActionPerformed(evt);
            }
        });

        label_vogal1.setText("Vogal");

        label_cripto1.setText("Criptografado");

        label_cripto2.setText("Criptografado");

        label_vogal2.setText("Vogal");

        btn_descriptografar.setText("Descriptografar");
        btn_descriptografar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_descriptografarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldVogal1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_vogal1)
                            .addComponent(label_cripto2)
                            .addComponent(TextFieldCripto2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_cripto1)
                                    .addComponent(TextFieldCripto1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextFieldVogal2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_vogal2)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(btn_criptografar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btn_descriptografar)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_vogal1)
                    .addComponent(label_cripto1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldVogal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldCripto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_criptografar)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_cripto2)
                    .addComponent(label_vogal2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldCripto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldVogal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_descriptografar)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_criptografarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_criptografarActionPerformed
        // TODO add your handling code here:
               
        String valor = TextFieldVogal1.getText();
        boolean continuar = false;

        
        for (int i = 0; i < vogais.length; i++) {
            if (valor.equals(vogais[i])){
             continuar=true;   
            }         
           
        }
        
        if (continuar){
        int crip = Arrays.binarySearch(vogais, valor);        
        TextFieldCripto1.setText(String.valueOf(crip+1));
        }else{
            JOptionPane.showMessageDialog(null, "Valor invalido, Digite uma vogal");
            TextFieldVogal1.setText("");
            TextFieldCripto1.setText("");
        }
    }//GEN-LAST:event_btn_criptografarActionPerformed

    private void btn_descriptografarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_descriptografarActionPerformed
        int[] numeros = {1,2,3,4,5};        
        int valor = Integer.parseInt(TextFieldCripto2.getText());
        boolean continuar = false;

        
        for (int i = 0; i < numeros.length; i++) {
            if (numeros[i] == valor){   
                continuar=true;
            } else {
            }         
           
        }
        
        if (continuar){
        
        TextFieldVogal2.setText(vogais[valor-1]);
        }else{
            JOptionPane.showMessageDialog(null, "Valor invalido, Digite uma número entre 1 e 5");
            TextFieldCripto2.setText("");
            TextFieldVogal2.setText("");
        }
    }//GEN-LAST:event_btn_descriptografarActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {                
                new Inicio().setVisible(true);
                
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextFieldCripto1;
    private javax.swing.JTextField TextFieldCripto2;
    private javax.swing.JTextField TextFieldVogal1;
    private javax.swing.JTextField TextFieldVogal2;
    private javax.swing.JButton btn_criptografar;
    private javax.swing.JButton btn_descriptografar;
    private javax.swing.JLabel label_cripto1;
    private javax.swing.JLabel label_cripto2;
    private javax.swing.JLabel label_vogal1;
    private javax.swing.JLabel label_vogal2;
    // End of variables declaration//GEN-END:variables
}
